const DATA = [
    {
        id: "1",
        title: "The Pentecost day",
        date: "2020-06-06",
        time: "12.45mins",
        preacher: "Wycliff",
        photo:"../assets/images/wycliff.jpg",
    },
    {
        id: "2",
        title: "Act fast",
        date: "2021-03-25",
        time: "40mins",
        preacher: "Pr.Kato",
        photo:"../assets/images/wycliff.jpg",
    },
    {
        id: "3",
        title: "Recognising the voice of God",
        date: "2021-01-05",
        time: "38mins",
        preacher: "Apostle Julliet",
        photo:"../assets/images/wycliff.jpg",
    },
    {
        id: "4",
        title: "Recognising the voice of God",
        date: "2021-01-05",
        time: "38mins",
        preacher: "Apostle Julliet",
        photo:"../assets/images/wycliff.jpg",
    },
    {
        id: "5",
        title: "Recognising the voice of God",
        date: "2021-01-05",
        time: "38mins",
        preacher: "Apostle Julliet",
        photo:"../assets/images/wycliff.jpg",
    },
    {
        id: "6",
        title: "Recognising the voice of God",
        date: "2021-01-05",
        time: "38mins",
        preacher: "Apostle Julliet",
        photo:"../assets/images/wycliff.jpg",
    },
    {
        id: "7",
        title: "Recognising the voice of God",
        date: "2021-01-05",
        time: "38mins",
        preacher: "Apostle Julliet",
        photo:"../assets/images/wycliff.jpg",
    },
    {
        id: "8",
        title: "Recognising the voice of God",
        date: "2021-01-05",
        time: "38mins",
        preacher: "Apostle Julliet",
        photo:"../assets/images/wycliff.jpg",
    },
    {
        id: "9",
        title: "Recognising the voice of God",
        date: "2021-01-05",
        time: "38mins",
        preacher: "Apostle Julliet",
        photo:"../assets/images/wycliff.jpg",
    },
    {
        id: "10",
        title: "Recognising the voice of God",
        date: "2021-01-05",
        time: "38mins",
        preacher: "Apostle Julliet",
        photo:"../assets/images/wycliff.jpg",
    }
]

export default DATA;